// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package main

import (
	"context"
	"sync"

	"github.com/google/go-containerregistry/pkg/name"
	v1 "github.com/google/go-containerregistry/pkg/v1"
	"github.com/google/go-containerregistry/pkg/v1/mutate"
)

// Ensure, that mockNixBuilderClient does implement nixBuilderClient.
// If this is not the case, regenerate this file with moq.
var _ nixBuilderClient = &mockNixBuilderClient{}

// mockNixBuilderClient is a mock implementation of nixBuilderClient.
//
//	func TestSomethingThatUsesnixBuilderClient(t *testing.T) {
//
//		// make and configure a mocked nixBuilderClient
//		mockednixBuilderClient := &mockNixBuilderClient{
//			BuildPlatformImageFunc: func(contextMoqParam context.Context, s string, reference name.Reference, platform *v1.Platform, imageOptionMoqParams ...imageOption) (string, error) {
//				panic("mock out the BuildPlatformImage method")
//			},
//			GetImageBuilderTypeFunc: func(contextMoqParam context.Context, s string, reference name.Reference, platform *v1.Platform, imageOptionMoqParams ...imageOption) (BuilderType, error) {
//				panic("mock out the GetImageBuilderType method")
//			},
//		}
//
//		// use mockednixBuilderClient in code that requires nixBuilderClient
//		// and then make assertions.
//
//	}
type mockNixBuilderClient struct {
	// BuildPlatformImageFunc mocks the BuildPlatformImage method.
	BuildPlatformImageFunc func(contextMoqParam context.Context, s string, reference name.Reference, platform *v1.Platform, imageOptionMoqParams ...imageOption) (string, error)

	// GetImageBuilderTypeFunc mocks the GetImageBuilderType method.
	GetImageBuilderTypeFunc func(contextMoqParam context.Context, s string, reference name.Reference, platform *v1.Platform, imageOptionMoqParams ...imageOption) (BuilderType, error)

	// calls tracks calls to the methods.
	calls struct {
		// BuildPlatformImage holds details about calls to the BuildPlatformImage method.
		BuildPlatformImage []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
			// Reference is the reference argument value.
			Reference name.Reference
			// Platform is the platform argument value.
			Platform *v1.Platform
			// ImageOptionMoqParams is the imageOptionMoqParams argument value.
			ImageOptionMoqParams []imageOption
		}
		// GetImageBuilderType holds details about calls to the GetImageBuilderType method.
		GetImageBuilderType []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
			// Reference is the reference argument value.
			Reference name.Reference
			// Platform is the platform argument value.
			Platform *v1.Platform
			// ImageOptionMoqParams is the imageOptionMoqParams argument value.
			ImageOptionMoqParams []imageOption
		}
	}
	lockBuildPlatformImage  sync.RWMutex
	lockGetImageBuilderType sync.RWMutex
}

// BuildPlatformImage calls BuildPlatformImageFunc.
func (mock *mockNixBuilderClient) BuildPlatformImage(contextMoqParam context.Context, s string, reference name.Reference, platform *v1.Platform, imageOptionMoqParams ...imageOption) (string, error) {
	callInfo := struct {
		ContextMoqParam      context.Context
		S                    string
		Reference            name.Reference
		Platform             *v1.Platform
		ImageOptionMoqParams []imageOption
	}{
		ContextMoqParam:      contextMoqParam,
		S:                    s,
		Reference:            reference,
		Platform:             platform,
		ImageOptionMoqParams: imageOptionMoqParams,
	}
	mock.lockBuildPlatformImage.Lock()
	mock.calls.BuildPlatformImage = append(mock.calls.BuildPlatformImage, callInfo)
	mock.lockBuildPlatformImage.Unlock()
	if mock.BuildPlatformImageFunc == nil {
		var (
			sOut   string
			errOut error
		)
		return sOut, errOut
	}
	return mock.BuildPlatformImageFunc(contextMoqParam, s, reference, platform, imageOptionMoqParams...)
}

// BuildPlatformImageCalls gets all the calls that were made to BuildPlatformImage.
// Check the length with:
//
//	len(mockednixBuilderClient.BuildPlatformImageCalls())
func (mock *mockNixBuilderClient) BuildPlatformImageCalls() []struct {
	ContextMoqParam      context.Context
	S                    string
	Reference            name.Reference
	Platform             *v1.Platform
	ImageOptionMoqParams []imageOption
} {
	var calls []struct {
		ContextMoqParam      context.Context
		S                    string
		Reference            name.Reference
		Platform             *v1.Platform
		ImageOptionMoqParams []imageOption
	}
	mock.lockBuildPlatformImage.RLock()
	calls = mock.calls.BuildPlatformImage
	mock.lockBuildPlatformImage.RUnlock()
	return calls
}

// GetImageBuilderType calls GetImageBuilderTypeFunc.
func (mock *mockNixBuilderClient) GetImageBuilderType(contextMoqParam context.Context, s string, reference name.Reference, platform *v1.Platform, imageOptionMoqParams ...imageOption) (BuilderType, error) {
	callInfo := struct {
		ContextMoqParam      context.Context
		S                    string
		Reference            name.Reference
		Platform             *v1.Platform
		ImageOptionMoqParams []imageOption
	}{
		ContextMoqParam:      contextMoqParam,
		S:                    s,
		Reference:            reference,
		Platform:             platform,
		ImageOptionMoqParams: imageOptionMoqParams,
	}
	mock.lockGetImageBuilderType.Lock()
	mock.calls.GetImageBuilderType = append(mock.calls.GetImageBuilderType, callInfo)
	mock.lockGetImageBuilderType.Unlock()
	if mock.GetImageBuilderTypeFunc == nil {
		var (
			builderTypeOut BuilderType
			errOut         error
		)
		return builderTypeOut, errOut
	}
	return mock.GetImageBuilderTypeFunc(contextMoqParam, s, reference, platform, imageOptionMoqParams...)
}

// GetImageBuilderTypeCalls gets all the calls that were made to GetImageBuilderType.
// Check the length with:
//
//	len(mockednixBuilderClient.GetImageBuilderTypeCalls())
func (mock *mockNixBuilderClient) GetImageBuilderTypeCalls() []struct {
	ContextMoqParam      context.Context
	S                    string
	Reference            name.Reference
	Platform             *v1.Platform
	ImageOptionMoqParams []imageOption
} {
	var calls []struct {
		ContextMoqParam      context.Context
		S                    string
		Reference            name.Reference
		Platform             *v1.Platform
		ImageOptionMoqParams []imageOption
	}
	mock.lockGetImageBuilderType.RLock()
	calls = mock.calls.GetImageBuilderType
	mock.lockGetImageBuilderType.RUnlock()
	return calls
}

// Ensure, that mockContainerBuilderClient does implement containerBuilderClient.
// If this is not the case, regenerate this file with moq.
var _ containerBuilderClient = &mockContainerBuilderClient{}

// mockContainerBuilderClient is a mock implementation of containerBuilderClient.
//
//	func TestSomethingThatUsescontainerBuilderClient(t *testing.T) {
//
//		// make and configure a mocked containerBuilderClient
//		mockedcontainerBuilderClient := &mockContainerBuilderClient{
//			CheckPushPermissionFunc: func(reference name.Reference) error {
//				panic("mock out the CheckPushPermission method")
//			},
//			LoadImageFunc: func(contextMoqParam context.Context, reference name.Reference, s string) (name.Reference, error) {
//				panic("mock out the LoadImage method")
//			},
//			LoadStreamImageFunc: func(contextMoqParam context.Context, reference name.Reference, s string) (name.Reference, error) {
//				panic("mock out the LoadStreamImage method")
//			},
//			PushImageFunc: func(reference name.Reference) error {
//				panic("mock out the PushImage method")
//			},
//			PushManifestFunc: func(reference name.Reference, indexAddendums []mutate.IndexAddendum) error {
//				panic("mock out the PushManifest method")
//			},
//			PushPlatformImageFunc: func(reference name.Reference, platform *v1.Platform) (mutate.IndexAddendum, error) {
//				panic("mock out the PushPlatformImage method")
//			},
//			TagImageFunc: func(contextMoqParam context.Context, reference1 name.Reference, reference2 name.Reference) error {
//				panic("mock out the TagImage method")
//			},
//			TrackImageFunc: func(reference name.Reference) error {
//				panic("mock out the TrackImage method")
//			},
//		}
//
//		// use mockedcontainerBuilderClient in code that requires containerBuilderClient
//		// and then make assertions.
//
//	}
type mockContainerBuilderClient struct {
	// CheckPushPermissionFunc mocks the CheckPushPermission method.
	CheckPushPermissionFunc func(reference name.Reference) error

	// LoadImageFunc mocks the LoadImage method.
	LoadImageFunc func(contextMoqParam context.Context, reference name.Reference, s string) (name.Reference, error)

	// LoadStreamImageFunc mocks the LoadStreamImage method.
	LoadStreamImageFunc func(contextMoqParam context.Context, reference name.Reference, s string) (name.Reference, error)

	// PushImageFunc mocks the PushImage method.
	PushImageFunc func(reference name.Reference) error

	// PushManifestFunc mocks the PushManifest method.
	PushManifestFunc func(reference name.Reference, indexAddendums []mutate.IndexAddendum) error

	// PushPlatformImageFunc mocks the PushPlatformImage method.
	PushPlatformImageFunc func(reference name.Reference, platform *v1.Platform) (mutate.IndexAddendum, error)

	// TagImageFunc mocks the TagImage method.
	TagImageFunc func(contextMoqParam context.Context, reference1 name.Reference, reference2 name.Reference) error

	// TrackImageFunc mocks the TrackImage method.
	TrackImageFunc func(reference name.Reference) error

	// calls tracks calls to the methods.
	calls struct {
		// CheckPushPermission holds details about calls to the CheckPushPermission method.
		CheckPushPermission []struct {
			// Reference is the reference argument value.
			Reference name.Reference
		}
		// LoadImage holds details about calls to the LoadImage method.
		LoadImage []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Reference is the reference argument value.
			Reference name.Reference
			// S is the s argument value.
			S string
		}
		// LoadStreamImage holds details about calls to the LoadStreamImage method.
		LoadStreamImage []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Reference is the reference argument value.
			Reference name.Reference
			// S is the s argument value.
			S string
		}
		// PushImage holds details about calls to the PushImage method.
		PushImage []struct {
			// Reference is the reference argument value.
			Reference name.Reference
		}
		// PushManifest holds details about calls to the PushManifest method.
		PushManifest []struct {
			// Reference is the reference argument value.
			Reference name.Reference
			// IndexAddendums is the indexAddendums argument value.
			IndexAddendums []mutate.IndexAddendum
		}
		// PushPlatformImage holds details about calls to the PushPlatformImage method.
		PushPlatformImage []struct {
			// Reference is the reference argument value.
			Reference name.Reference
			// Platform is the platform argument value.
			Platform *v1.Platform
		}
		// TagImage holds details about calls to the TagImage method.
		TagImage []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Reference1 is the reference1 argument value.
			Reference1 name.Reference
			// Reference2 is the reference2 argument value.
			Reference2 name.Reference
		}
		// TrackImage holds details about calls to the TrackImage method.
		TrackImage []struct {
			// Reference is the reference argument value.
			Reference name.Reference
		}
	}
	lockCheckPushPermission sync.RWMutex
	lockLoadImage           sync.RWMutex
	lockLoadStreamImage     sync.RWMutex
	lockPushImage           sync.RWMutex
	lockPushManifest        sync.RWMutex
	lockPushPlatformImage   sync.RWMutex
	lockTagImage            sync.RWMutex
	lockTrackImage          sync.RWMutex
}

// CheckPushPermission calls CheckPushPermissionFunc.
func (mock *mockContainerBuilderClient) CheckPushPermission(reference name.Reference) error {
	callInfo := struct {
		Reference name.Reference
	}{
		Reference: reference,
	}
	mock.lockCheckPushPermission.Lock()
	mock.calls.CheckPushPermission = append(mock.calls.CheckPushPermission, callInfo)
	mock.lockCheckPushPermission.Unlock()
	if mock.CheckPushPermissionFunc == nil {
		var errOut error
		return errOut
	}
	return mock.CheckPushPermissionFunc(reference)
}

// CheckPushPermissionCalls gets all the calls that were made to CheckPushPermission.
// Check the length with:
//
//	len(mockedcontainerBuilderClient.CheckPushPermissionCalls())
func (mock *mockContainerBuilderClient) CheckPushPermissionCalls() []struct {
	Reference name.Reference
} {
	var calls []struct {
		Reference name.Reference
	}
	mock.lockCheckPushPermission.RLock()
	calls = mock.calls.CheckPushPermission
	mock.lockCheckPushPermission.RUnlock()
	return calls
}

// LoadImage calls LoadImageFunc.
func (mock *mockContainerBuilderClient) LoadImage(contextMoqParam context.Context, reference name.Reference, s string) (name.Reference, error) {
	callInfo := struct {
		ContextMoqParam context.Context
		Reference       name.Reference
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		Reference:       reference,
		S:               s,
	}
	mock.lockLoadImage.Lock()
	mock.calls.LoadImage = append(mock.calls.LoadImage, callInfo)
	mock.lockLoadImage.Unlock()
	if mock.LoadImageFunc == nil {
		var (
			referenceOut name.Reference
			errOut       error
		)
		return referenceOut, errOut
	}
	return mock.LoadImageFunc(contextMoqParam, reference, s)
}

// LoadImageCalls gets all the calls that were made to LoadImage.
// Check the length with:
//
//	len(mockedcontainerBuilderClient.LoadImageCalls())
func (mock *mockContainerBuilderClient) LoadImageCalls() []struct {
	ContextMoqParam context.Context
	Reference       name.Reference
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		Reference       name.Reference
		S               string
	}
	mock.lockLoadImage.RLock()
	calls = mock.calls.LoadImage
	mock.lockLoadImage.RUnlock()
	return calls
}

// LoadStreamImage calls LoadStreamImageFunc.
func (mock *mockContainerBuilderClient) LoadStreamImage(contextMoqParam context.Context, reference name.Reference, s string) (name.Reference, error) {
	callInfo := struct {
		ContextMoqParam context.Context
		Reference       name.Reference
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		Reference:       reference,
		S:               s,
	}
	mock.lockLoadStreamImage.Lock()
	mock.calls.LoadStreamImage = append(mock.calls.LoadStreamImage, callInfo)
	mock.lockLoadStreamImage.Unlock()
	if mock.LoadStreamImageFunc == nil {
		var (
			referenceOut name.Reference
			errOut       error
		)
		return referenceOut, errOut
	}
	return mock.LoadStreamImageFunc(contextMoqParam, reference, s)
}

// LoadStreamImageCalls gets all the calls that were made to LoadStreamImage.
// Check the length with:
//
//	len(mockedcontainerBuilderClient.LoadStreamImageCalls())
func (mock *mockContainerBuilderClient) LoadStreamImageCalls() []struct {
	ContextMoqParam context.Context
	Reference       name.Reference
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		Reference       name.Reference
		S               string
	}
	mock.lockLoadStreamImage.RLock()
	calls = mock.calls.LoadStreamImage
	mock.lockLoadStreamImage.RUnlock()
	return calls
}

// PushImage calls PushImageFunc.
func (mock *mockContainerBuilderClient) PushImage(reference name.Reference) error {
	callInfo := struct {
		Reference name.Reference
	}{
		Reference: reference,
	}
	mock.lockPushImage.Lock()
	mock.calls.PushImage = append(mock.calls.PushImage, callInfo)
	mock.lockPushImage.Unlock()
	if mock.PushImageFunc == nil {
		var errOut error
		return errOut
	}
	return mock.PushImageFunc(reference)
}

// PushImageCalls gets all the calls that were made to PushImage.
// Check the length with:
//
//	len(mockedcontainerBuilderClient.PushImageCalls())
func (mock *mockContainerBuilderClient) PushImageCalls() []struct {
	Reference name.Reference
} {
	var calls []struct {
		Reference name.Reference
	}
	mock.lockPushImage.RLock()
	calls = mock.calls.PushImage
	mock.lockPushImage.RUnlock()
	return calls
}

// PushManifest calls PushManifestFunc.
func (mock *mockContainerBuilderClient) PushManifest(reference name.Reference, indexAddendums []mutate.IndexAddendum) error {
	callInfo := struct {
		Reference      name.Reference
		IndexAddendums []mutate.IndexAddendum
	}{
		Reference:      reference,
		IndexAddendums: indexAddendums,
	}
	mock.lockPushManifest.Lock()
	mock.calls.PushManifest = append(mock.calls.PushManifest, callInfo)
	mock.lockPushManifest.Unlock()
	if mock.PushManifestFunc == nil {
		var errOut error
		return errOut
	}
	return mock.PushManifestFunc(reference, indexAddendums)
}

// PushManifestCalls gets all the calls that were made to PushManifest.
// Check the length with:
//
//	len(mockedcontainerBuilderClient.PushManifestCalls())
func (mock *mockContainerBuilderClient) PushManifestCalls() []struct {
	Reference      name.Reference
	IndexAddendums []mutate.IndexAddendum
} {
	var calls []struct {
		Reference      name.Reference
		IndexAddendums []mutate.IndexAddendum
	}
	mock.lockPushManifest.RLock()
	calls = mock.calls.PushManifest
	mock.lockPushManifest.RUnlock()
	return calls
}

// PushPlatformImage calls PushPlatformImageFunc.
func (mock *mockContainerBuilderClient) PushPlatformImage(reference name.Reference, platform *v1.Platform) (mutate.IndexAddendum, error) {
	callInfo := struct {
		Reference name.Reference
		Platform  *v1.Platform
	}{
		Reference: reference,
		Platform:  platform,
	}
	mock.lockPushPlatformImage.Lock()
	mock.calls.PushPlatformImage = append(mock.calls.PushPlatformImage, callInfo)
	mock.lockPushPlatformImage.Unlock()
	if mock.PushPlatformImageFunc == nil {
		var (
			indexAddendumOut mutate.IndexAddendum
			errOut           error
		)
		return indexAddendumOut, errOut
	}
	return mock.PushPlatformImageFunc(reference, platform)
}

// PushPlatformImageCalls gets all the calls that were made to PushPlatformImage.
// Check the length with:
//
//	len(mockedcontainerBuilderClient.PushPlatformImageCalls())
func (mock *mockContainerBuilderClient) PushPlatformImageCalls() []struct {
	Reference name.Reference
	Platform  *v1.Platform
} {
	var calls []struct {
		Reference name.Reference
		Platform  *v1.Platform
	}
	mock.lockPushPlatformImage.RLock()
	calls = mock.calls.PushPlatformImage
	mock.lockPushPlatformImage.RUnlock()
	return calls
}

// TagImage calls TagImageFunc.
func (mock *mockContainerBuilderClient) TagImage(contextMoqParam context.Context, reference1 name.Reference, reference2 name.Reference) error {
	callInfo := struct {
		ContextMoqParam context.Context
		Reference1      name.Reference
		Reference2      name.Reference
	}{
		ContextMoqParam: contextMoqParam,
		Reference1:      reference1,
		Reference2:      reference2,
	}
	mock.lockTagImage.Lock()
	mock.calls.TagImage = append(mock.calls.TagImage, callInfo)
	mock.lockTagImage.Unlock()
	if mock.TagImageFunc == nil {
		var errOut error
		return errOut
	}
	return mock.TagImageFunc(contextMoqParam, reference1, reference2)
}

// TagImageCalls gets all the calls that were made to TagImage.
// Check the length with:
//
//	len(mockedcontainerBuilderClient.TagImageCalls())
func (mock *mockContainerBuilderClient) TagImageCalls() []struct {
	ContextMoqParam context.Context
	Reference1      name.Reference
	Reference2      name.Reference
} {
	var calls []struct {
		ContextMoqParam context.Context
		Reference1      name.Reference
		Reference2      name.Reference
	}
	mock.lockTagImage.RLock()
	calls = mock.calls.TagImage
	mock.lockTagImage.RUnlock()
	return calls
}

// TrackImage calls TrackImageFunc.
func (mock *mockContainerBuilderClient) TrackImage(reference name.Reference) error {
	callInfo := struct {
		Reference name.Reference
	}{
		Reference: reference,
	}
	mock.lockTrackImage.Lock()
	mock.calls.TrackImage = append(mock.calls.TrackImage, callInfo)
	mock.lockTrackImage.Unlock()
	if mock.TrackImageFunc == nil {
		var errOut error
		return errOut
	}
	return mock.TrackImageFunc(reference)
}

// TrackImageCalls gets all the calls that were made to TrackImage.
// Check the length with:
//
//	len(mockedcontainerBuilderClient.TrackImageCalls())
func (mock *mockContainerBuilderClient) TrackImageCalls() []struct {
	Reference name.Reference
} {
	var calls []struct {
		Reference name.Reference
	}
	mock.lockTrackImage.RLock()
	calls = mock.calls.TrackImage
	mock.lockTrackImage.RUnlock()
	return calls
}
